# Generated by Django 5.1.7 on 2025-03-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestcourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcourse',
            name='primary',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
