# Generated by Django 5.1.7 on 2025-04-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('file_pdf', models.FileField(upload_to='uploads/pdfs/')),
            ],
        ),
    ]
