# Generated by Django 5.1.7 on 2025-04-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=10)),
                ('decs', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=10)),
            ],
        ),
    ]
