# Generated by Django 5.1.7 on 2025-03-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stafflogin',
            fields=[
                ('staff_email', models.CharField(max_length=50)),
                ('staff_password', models.CharField(max_length=50)),
                ('staff_name', models.CharField(max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
