# Generated by Django 5.1.7 on 2025-03-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newcourseenroled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30)),
                ('course_code', models.CharField(max_length=10)),
                ('course_instructor', models.CharField(max_length=30)),
                ('course_complete', models.CharField(max_length=3)),
                ('student_id', models.CharField(max_length=30)),
            ],
        ),
    ]
