# Generated by Django 5.1.7 on 2025-03-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newcourseenroled', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcourseenroled',
            name='primary',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
